name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run unit tests
        run: python -m unittest discover -s tests

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish
